blockchain/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home,name='blockchain-home'),
    path('add_product/', views.add_product,name='blockchain-add-product'),
    path('about/', views.about,name='blockchain-about'),
    path('tracking/', views.tracking, name='product-tracking'),
    path('enter/',views.enter_prod_id, name="blockchain-your-product"),
]

blockchain_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',user_views.register, name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/',user_views.profile, name='profile'),
    path('', include('blockchain.urls')),
]

blockchain/models.py
from django.db import models
from hashlib import sha256
import datetime
import logging
import pytz
from django.urls import reverse

UNITS = [
    ('kg', 'kg'),
    ('tons', 'tons'),
    ('bags', 'bags'),
    ('pieces', 'pieces'),
    ]
class Transaction (models.Model):
    index = models.IntegerField(auto_created=True, blank=True,null=True)
    product_id = models.IntegerField()
    common_name= models.CharField(blank=True, max_length=105,null=True)
    #expiry_date = models.DateTimeField(blank=True,null=True)
    expiry_date = models.CharField(max_length=50, null=True)
    country = models.CharField(max_length=50, null=True)
    quantity = models.IntegerField()
    unit = models.CharField(choices=UNITS, default='', max_length=6)
    company = models.CharField(blank=True, max_length=105,null=True)
    executor = models.CharField(blank=True, max_length=105,null=True)
    
    def __str__(self):
        return "Transaction " + str(self.index)

class ProducerModel(models.Model):
    index = models.IntegerField(auto_created=True, blank=True,null=True)
    product_id = models.IntegerField()
    current_date = models.DateTimeField(auto_now=True)
    expire_date = models.DateTimeField(blank=True,null=True)
    country = models.CharField(max_length=50)
    amount = models.IntegerField()
    common_name= models.TextField(blank=True, max_length=255,null=True)


class ShipperModel(models.Model):
    index = models.IntegerField(auto_created=True, blank=True,null=True)
    product_id = models.IntegerField()
    current_date = models.DateTimeField(auto_now=True)
    expire_date = models.DateTimeField(blank=True,null=True)
    country = models.CharField(max_length=50)
    amount = models.IntegerField()
    common_name= models.TextField(blank=True, max_length=255,null=True)

   
class WholesalerModel(models.Model):
    index = models.IntegerField(auto_created=True, blank=True,null=True)
    product_id = models.IntegerField()
    current_date = models.DateTimeField(auto_now=True)
    expire_date = models.DateTimeField(blank=True,null=True)
    country = models.CharField(max_length=50)
    amount = models.IntegerField()
    common_name= models.TextField(blank=True, max_length=255,null=True)


class DetailerModel(models.Model):
    index = models.IntegerField(auto_created=True, blank=True,null=True)
    product_id = models.IntegerField()
    current_date = models.DateTimeField(auto_now=True)
    expire_date = models.DateTimeField(blank=True,null=True)
    country = models.CharField(max_length=50)
    amount = models.IntegerField()
    common_name= models.TextField(blank=True, max_length=100,null=True)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from random import randrange
from .services import validate_address

links =  [
    ('producer', 'Producer'),
    ('shipper', 'Shipper'),
    ('wholesaler', 'Wholesaler'),
    ('detailer', 'Detailer'),
    ]

class UserProfile(AbstractUser):
    widget = models.CharField(max_length=20, choices=links,verbose_name="Choose your link",default=links[0])
    nonce = models.IntegerField(default=randrange(1000000,9999999))
    public_address = models.CharField(max_length=20,validators=[validate_address])

blockchain/forms.py
from django.forms import ModelForm
from .models import Transaction
from web3 import Web3
#from betterforms.multiform import MultiModelForm


class ProducerForm(ModelForm):
    class Meta:
        model = Transaction
        fields = ['product_id','common_name','expiry_date','country','quantity','company','executor']        

class ShipperForm(ModelForm):
    class Meta:
        model = Transaction
        fields = ['product_id','common_name','country','quantity','company','executor']

class WholesalerForm(ModelForm):
    class Meta:
        model = Transaction
        fields = ['product_id','common_name','country','quantity','company','executor']
   
class DetailerForm(ModelForm):
    class Meta:
        model = Transaction
        fields = ['product_id','common_name','country','quantity','company']

# class LinksMultiForm(MultiModelForm):
#     form_classes = {
#         'producer': ProducerForm,
#         'shipper': ShipperForm,
#         'wholesaler': WholesalerForm,
#         'detailer': DetailerForm,
#     }
    

blockchain/views.py
from django.shortcuts import render,redirect
from .forms import ProducerForm,ShipperForm,DetailerForm,WholesalerForm
from .models import ProducerModel,ShipperModel,DetailerModel,WholesalerModel
from django.contrib import messages
from rest_framework import generics,mixins
from rest_framework.generics import CreateAPIView,ListAPIView
from rest_framework.views import APIView
from django.db import models

from .services import TransactionService
from django.contrib.auth.decorators import login_required


tx_service = TransactionService()
tx_service.setup_blockchain_connection()


def home(request):
    tx_service.setup_contract("user")
    setup_forms_fields(request)
    return render(request,'blockchain/home.html')

def setup_forms_fields(request):
    producer_fields = list(ProducerForm.base_fields)
    shipper_fields = list(ShipperForm.base_fields)
    wholesaler_fields = list(WholesalerForm.base_fields)
    detailer_fields = list(DetailerForm.base_fields)

    request.session['producer_fields'] = producer_fields
    request.session['shipper_fields'] = shipper_fields
    request.session['wholesaler_fields'] = wholesaler_fields
    request.session['detailer_fields'] = detailer_fields

@login_required
def add_product(request):
    current_link = request.user.widget.lower()
    tx_service.setup_contract(current_link)

    if request.method == 'POST':
        if current_link == "producer":
            form_for_link = ProducerForm(request.POST)
        elif current_link == "shipper":
            form_for_link = ShipperForm(request.POST)
        elif current_link == "wholesaler":
            form_for_link = WholesalerForm(request.POST)
        elif current_link == "detailer":
            form_for_link = DetailerForm(request.POST)
        #form_class = LinksMultiForm(request.POST)
        #form_for_link= form_class[current_link]
        
        if form_for_link.is_valid():
            tx_service.add_link(form_for_link)
            form_for_link.save(commit=False)
            print("Form posted correctly!")
            print("Index: ",form_for_link.cleaned_data.get("product_id"))
            print("Common name: ", form_for_link.cleaned_data.get("common_name"))
            messages.success(request, 'You posted a form successfully')
            return redirect('blockchain-home')
    else:
        if current_link == "producer":
            form_for_link = ProducerForm()
        elif current_link == "shipper":
            form_for_link = ShipperForm()
        elif current_link == "wholesaler":
            form_for_link = WholesalerForm()
        elif current_link == "detailer":
            form_for_link = DetailerForm()
        #form_class = LinksMultiForm()
        #form_for_link= form_class[current_link]

    return render(request,'blockchain/add_product.html',{'form': form_for_link})

def about(request):
    return render(request,'blockchain/about.html',{'title':'About'})

def enter_prod_id(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        received_info = tx_service.get_all_links(product_id)

        print("Received product id: {}".format(received_info))
        request.session['tracked_product_id'] = received_info

        return redirect('/tracking')
    
    return render(request, 'blockchain/enter_prod_id.html')
    
def tracking(request):
    received_info = request.session['tracked_product_id']

    producer_fields= dict(zip(request.session['producer_fields'],received_info['producer']))
    shipper_fields= dict(zip(request.session['shipper_fields'],received_info['shipper']))
    wholesaler_fields = dict(zip(request.session['wholesaler_fields'],received_info['wholesaler']))
    detailer_fields = dict(zip(request.session['detailer_fields'],received_info['detailer']))
    
    tracked_product = {
        'producer_fields': producer_fields,
        'shipper_fields': shipper_fields,
        'wholesaler_fields': wholesaler_fields,
        'detailer_fields': detailer_fields,
    }
    return render(request, 'blockchain/tracking.html', context = tracked_product)
  

blockchain/templates/blockchain/about.html
{% extends "blockchain/base.html" %}
{% block content%}
    <h1> Blockchain Website Info</h1>
{%endblock content%}

blockchain/templates/blockchain/add_product.html
{% extends "blockchain/base.html" %}

{% load crispy_forms_tags %}
{% block content%}


<div class="container container-form">
<h1> Fill the form for {{user.get_widget_display}}</h1>
<form method="POST" >
  {% csrf_token %}
  <fieldset class="form-group ml-2 col-md-8">
      {{form|crispy}}
  </fieldset>
  <div class="form-group ml-2">
      <button class="btn btn-outline-info" type="submit">Sign up</button>
  </div>
</form>  
</div>  
{%endblock content%}

blockchain/templates/blockchain/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blockchain/main.css' %}">

    {%if title%}
        <title>SupBlock - {{title}}</title>
    {%else%}
        <title>SupBlock </title>
    {%endif%}
</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'blockchain-home' %}">SupBlock</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'blockchain-home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'blockchain-about' %}">About</a>
                <a class="nav-item nav-link" href="{% url 'blockchain-your-product' %}">Your product</a>
                <a class="nav-item nav-link" href="{% url 'blockchain-add-product' %}">Add link</a>
                {%else%}
                <a class="nav-item nav-link" href="{% url 'blockchain-home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'blockchain-about' %}">About</a>
                <a class="nav-item nav-link" href="{% url 'blockchain-your-product' %}">Your product</a>
                {% endif %}
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main role="main" class="container container-menu">
          <div class="col-md-12">
            {% if messages %}
                {% for message in messages%}
                    <div class="alert alert-{{ message.tags}}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif%}  
            {% block content %}{% endblock %}
          </div>
        </div>
      </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <script src ="{% static 'blockchain/App.js' %}" type="text/JavaScript"></script>
    <script src="https://rawgit.com/ethereum/web3.js/develop/dist/web3.js"></script>
</body>
</html>

blockchain/templates/blockchain/enter_prod_id.html
{% extends "blockchain/base.html" %}
{% load static %}
{% block content%}
<div class="row justify-content-md-center">
    <h1><b>Enter product ID</b></h1>
</div>
<div class="row justify-content-md-center">
    <form method="POST">
        {% csrf_token %}
        <input type="number" name="product_id" placeholder="Your product id" required="required" min=1 max=65000 style="width: 9em">
        <div class="form-group text-center">
            <button class="btn btn-outline-info" type="submit">Check</button>
        </div>
    </form>
</div>
<div class="row justify-content-md-center">
    <img src="{% static 'blockchain/truck_on_road_img.png' %}" class="img-fluid" alt="Enter page image" width="300px" height="300px">
</div>
{%endblock content%}

blockchain/templates/blockchain/home.html
{% extends "blockchain/base.html" %}
{% load static %}
{% block content%}
<div class="row row-home">
    <div class = "col text-home">
        <h1><b>Welcome on SupBlock Platform</b></h1>
        <form>
            <button class="btn btn-outline-primary" formaction="{% url 'blockchain-your-product' %}">Track your product</button>
        </form>            
    </div>
    <div class = "col text-home">
        <img src="{% static 'blockchain/home_img.png' %}" class="img-fluid" alt="Home page image">
    </div>
</div>
{%endblock content%}

blockchain/templates/blockchain/tracking.html
{% extends "blockchain/base.html" %}

{% block content%}
<div class="container mt-3 mb-5">
    <div class="row">
        <div class="col-md-8">
            <h3>Product ID: {{id}}</h3>
            <ul class="timeline">
                <li>
                    <span></span>
                    <a href="#collapseOne" data-toggle="collapse">Producer</a>                            
                    <div id="collapseOne" class="collapse">
                        <div class="card-body">
                            <table class="table">
                                <tbody>
                                    {% for key,value in producer_fields.items %} 
                                    <tr>
                                        <th scope="row">{{key}}</th>
                                        <td>{{value}}</td>
                                    </tr>               
                                    {% endfor %}
                                </tbody>
                                </table>
                        </div>
                    </div>
                </li>
                <li>
                    <span></span>
                    <a href="#collapseTwo" data-toggle="collapse">Shipper</a>                            
                    <div id="collapseTwo" class="collapse" >
                        <div class="card-body">
                            <table class="table">
                                <tbody>
                                    {% for key,value in shipper_fields.items %} 
                                    <tr>
                                        <th scope="row">{{key}}</th>
                                        <td>{{value}}</td>
                                    </tr>               
                                    {% endfor %}
                                </tbody>
                                </table>
                        </div>
                    </div>
                </li>
                <li>
                    <span></span>
                    <a href="#collapseThree" data-toggle="collapse">Wholesaler</a>                            
                    <div id="collapseThree" class="collapse" >
                        <div class="card-body">
                            <table class="table">
                                <tbody>
                                    {% for key,value in wholesaler_fields.items %} 
                                    <tr>
                                        <th scope="row">{{key}}</th>
                                        <td>{{value}}</td>
                                    </tr>               
                                    {% endfor %}
                                </tbody>
                                </table>
                        </div>
                    </div>
                </li>

                <li>
                    <span></span>
                    <a href="#collapseFour" data-toggle="collapse">Detailer</a>                            
                    <div id="collapseFour" class="collapse" >
                        <div class="card-body">
                            <table class="table">
                                <tbody>
                                    {% for key,value in detailer_fields.items %} 
                                    <tr>
                                        <th scope="row">{{key}}</th>
                                        <td>{{value}}</td>
                                    </tr>               
                                    {% endfor %}
                                </tbody>
                                </table>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
{%endblock content%}